version: '3'
services:
  PERIC-mongodb:
    image: mongo:latest
    container_name: PERIC-mongodb
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - PERIC_mongo_data:/data/db
    env_file:
      - ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSW}
      - MONGO_INITDB_DATABASE=${MONGO_DB}
volumes:
  PERIC_mongo_data: